// Code generated by sqlc. DO NOT EDIT.
package dbgen

import "context"

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	var v int32
	err := q.db.QueryRow(ctx, ping).Scan(&v)
	return v, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	var v int64
	err := q.db.QueryRow(ctx, countOrganizations).Scan(&v)
	return v, err
}
